### PR TITLE
Add moitestset macro and transition contconic

### PR DESCRIPTION
**Pull request by blegat**
cc @odow

### CODE REVIEW

**Comment by joaquimg** [comment]
Nice! I was just thinking about that macro

**Comment by mlubin** [comment]
What's the intention of passing ``exclude`` to the individual tests? The `TestConfig` is meant to be used for disabling specific parts of a test.

**Comment by blegat** [comment]
It is to allow nested test lists like in contconic where `contconictest` calls `lintest`, `soctest`, `rsoctest` and `sdptest` which themself call `lin1test`, ...
With this multiple level, the user can exclude all the sdp tests with one string (e.g. conic solver not supporting SDP like ECOS) or disable just one of the sdp test (e.g. SDP solver that fails at one of the SDP test).
For this reason, the macro needs to pass the `exclude` list along because it does not know if it is calling a list of test or a test.
We could add additional complexity to avoid this but it might be easier to just ignore the `exclude` argument in case of a test.

**Comment by mlubin** [comment]
I find that a bit confusing. We should have two different concepts in the code:
- A single test like `linear1test` that gets passed a `TestConfig` only.
- A collection of tests like `contlinear`. These can include collections recursively. You can exclude individual tests. ~I'm not sure if it's necessary to support excluding subcollections.~ If we're going to allow excluding collections of tests, we need better documentation for what the collections tests.

**Comment by blegat** [comment]
I have added a `testset` argument to distinguish between the two cases and added documentation. Individual tests now do not need to have an `exclude` argument anymore

**Review by mlubin — APPROVED** [review]

**Pull request merged**
