### PR TITLE
Remove solver concept

### PR DESCRIPTION
**Pull request by blegat**
Quick fix for MOIT. I am not saying that this is how solvers should be replaced, it might be temporary. At least it is better that something failing :)

### CODE REVIEW

**Comment by mlubin** [comment]
LGTM

**Comment by joaquimg** [comment]
We needed parameters!
Just passing a function wont allow parameters.

**Comment by blegat** [comment]
@joaquimg What do you mean ? In CSDP, we do `() -> CSDP.CSDPInstance(printlevel=0)`.

**Comment by joaquimg** [comment]
That actually looks good

**Pull request merged**
